### ISSUE TITLE
libInjection version to use in ModSecurity

### ISSUE THREAD

**Issue by zimmerle** [client9/libinjection#124]
As you may know [SpiderLabs/ModSecurity](https://github.com/SpiderLabs/ModSecurity) uses libinjection. Due to historical reasons, ModSecurity source code contains part of the libInjection code. Therefore the updates are manual. 

I am looking forward to upgrade ModSecurity's libInjection version but I am not sure which commit to use.
Is there any specific commit that you recommend the utilization?

**Comment by client9** [comment]
Let me tag a new version, so you can get the latest.  Will do EOD.

thanks!

**Comment by client9** [comment]
Hi guys / @zimmerle 

I just tagged version 3.9.2

This DOES NOT contain any fixes for the recent bypasses.  It's just there to tag everything before I start work on the new stuff.

You may wish to try out a build with this just to make sure it works.  It's been 2.5 years since the last release.

Will update when 3.10.0 comes out.

regards,

n

**Comment by client9** [comment]
Ok, got a lot in this one.  I'll wait for feedback before tagging v3.10.0

**Comment by zimmerle** [comment]
Hi @client9, 

Thank you :) I think you might have forgotten to push the tag to the Git Repo.

**Comment by client9** [comment]
ah didn't tag since no feedback. 

I'll do it now.

**Comment by client9** [comment]
Oh 3.9.2 wasn't pushed.  Boo.

Ok you want 3.10.0 now.  Hopefully I did this correctly.  I'm a git failure.

**Comment by zimmerle** [comment]
That is fine ;) 3.10 it is.

 ModSecurity master branch is not up-to-date.

Thanks @client9.
